# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperformanceindicator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://regproject.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5bddcb238dc645828d6b8d8875330603 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_590381667d9849728535429b6e9ecdce }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: regproject.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5bddcb238dc645828d6b8d8875330603 }}/studentperformanceindicator:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperformanceindicator'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_34d45e6988f444d49cb700c4acb9ed49 }}
        images: 'regproject.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5bddcb238dc645828d6b8d8875330603 }}/studentperformanceindicator:${{ github.sha }}'